### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by DavidDavid360** [Jugheadbomb/engiesVSzombies#1]
How do you even start the game mode? on my server i have the plugin however i have no way of readying up. as no one can go to blue team to ready up as you cant switch teams, and when I have no cfg it does not start, i tried using the start bonus round command in chat and in the server terminal and have not managed to figure it out.

**Comment by Jugheadbomb** [comment]
I can't understand what are you talking about, please describe more precisely.

Gamemode starts at Waiting For Players stage, when everyone is red. After wfp stage, plugin randomly chooses zombie players to assign them to blue team, that's it. Every map start goes like this.

`sm_evz_startbonus` currently only works in-game (not as console). It uses additional argument to start specific bonus round from unique id section from config. For example: `sm_evz_startbonus 0` will set next round as bonus round (Low gravity), you can use command without arguments, so it will select random bonus round for next round.

**Comment by zudsniper** [comment]
Hello @Jugheadbomb & @DavidDavid360

I wanted to say something in hopes of clearing up any miscommunications here. This gamemode  begins at the "Waiting For Players" stage of tournament mode (`mp_tournament 1`), where, **in order to get going**, initiate the plugin and continue its functionality, **everyone must be on RED**. After this, the plugin will automatically & randomly select players to turn into zombies, moving them to BLU. The command `sm_evz_startbonus` is a command implemented to define what type of "bonus round" should be initiated, with the default being to randomly select between the options. 

@DavidDavid360 -- it seems like you're having trouble with the initial setup process. If you can provide more details as to exactly what steps, in order, you performed, what problems you encountered, and what functionality you expected, we could help you much more effectively. If you'd rather solve the issue via voice call, give me a ping and I can try to help. 

> P.S. @Jugheadbomb  
> I think it would be a good idea to have a more comprehensive guide or FAQ for newcomers in the `README.md`. This could be a very useful resource of step-by-step instructions, common hiccups and their fixes, and a deep dive into the different commands and their functions. (which would drive more server administrators to use the plugin) Just a thought, and I understand that creating documentation like that is time-consuming, and that is likely why you didn't already do so.   
> If you'd like to get in touch to discuss help on creating the aforementioned documentation, please reach out to me! My email is `me@zod.tf` and my Discord is just the same username as here, that being `zudsniper`. That said, no harm done if you'd rather not pursue this further. Thank you for reading this!

Cheers

**Comment by Jugheadbomb** [comment]
Seems `mp_tournament 1` causes "Waiting For Players" stage go infinitely. I made a commit that fixes that - it forces mp_tournament to 0 when plugin is loaded.

Also now if plugin is failed to parse config file, it will stop working.
